# Generated by Django 6.0.7 on 2026-08-05 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('movies', '0006_alter_seat_price_delete_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingseat',
            name='show',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookingseat', to='movies.show'),
        ),
    ]
