# Generated by Django 6.0.7 on 2026-08-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_bookingseat_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
