# Generated by Django 6.0.7 on 2026-08-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_booking_created_alter_bookingseat_show'),
        ('movies', '0006_alter_seat_price_delete_bookings'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bookingseat',
            constraint=models.UniqueConstraint(fields=('show', 'seat'), name='unique_show_seat'),
        ),
    ]
