# Generated by Django 6.0.7 on 2026-07-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_poster'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='show',
            constraint=models.UniqueConstraint(fields=('movie', 'theatre', 'date', 'time'), name='unique_show'),
        ),
    ]
