# Generated by Django 6.0.7 on 2026-07-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_show_unique_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
    ]
