# Generated by Django 6.0.7 on 2026-07-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_show_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
